### ISSUE TITLE
Sensor only finds playlists created by me

### ISSUE THREAD

**Issue by jrg89** [dnguyen800/spotify-playlist-sensor#1]
I've managed to get this setup today and it's great. I've noticed from your screenshots that you're getting curated playlists (Release Radar, etc) appearing in your sensor.
My sensor only seems to be pulling through playlists that I've created myself, not those created by others that I save to my library.

If I hit the API here: https://developer.spotify.com/console/get-current-user-playlists/?limit=6&offset= I do see the curated playlists here, so was wondering if you had any idea why they're not pulling through?

Thanks

**Comment by dnguyen800** [comment]
Sorry, I'm not sure why you're not getting playlists like Release Radar or Discovery Weekly showing up.  The sensor pulls my top 6 playlists listed as long as they are listed at the top of the Playlist section. Here is what it looks like on the Spotify Windows app:

![image](https://user-images.githubusercontent.com/25126347/59626089-cf3d5f00-90ef-11e9-98e2-881bd7700df6.png)

**Comment by bretteldridge** [comment]
I think it is a scope issue. The sensor.py file is not asking for the correct permissions.

The reason it works for you via the link is because you generate a key yourself with the correct permissions.

See issue 2 for more info.

**Comment by dnguyen800** [comment]
issue fixed in latest release, thanks @bretteldridge
