### ISSUE TITLE
Sensor not showing any playlists

### ISSUE THREAD

**Issue by klejejs** [dnguyen800/spotify-playlist-sensor#2]
When I am linking to spotify, my browser downloads a file and sensor shows that state is "6". There are no attributes available.
Do you have any solution?

**Comment by bretteldridge** [comment]
I can confirm this is happening for me also.

**Comment by bretteldridge** [comment]
OK. I am not an expert, but I have a solution for you.
The code does not include the correct scope for spotify. Not enough permissions.

You need to modify line 59 of the sensor.py file.
OLD: 
`SCOPE = 'user-read-playback-state user-modify-playback-state user-read-private'`
New:
`SCOPE = 'user-read-playback-state user-modify-playback-state user-read-private playlist-read-private'`

Once you do that, go back and delete the **.spotifyplaylist-token-cache** file from the main config folder.

Restart.

**Comment by klejejs** [comment]
Thank you! This helped.

**Comment by dwinnnspeaks** [comment]
Thanks for this. I'll update the scope to include your changes.

**Comment by dnguyen800** [comment]
Thanks for this @bretteldridge. I'll update the scope to include your changes.
