### ISSUE TITLE
Configuring Playlist Count is Not Documented Correctly.

### ISSUE THREAD

**Issue by bretteldridge** [dnguyen800/spotify-playlist-sensor#3]
In the instructions: 'Configuration options for sensor list'.

There says there is a key called: playlists
This key states it is an integer and it 'Selects the top x number of recent playlists.'

However, in the sensor.py file on line 35 it says:
`CONF_NUMBER_OF_PLAYLISTS = 'number_of_playlists'`

The key should actually be: number_of_playlists

**Comment by dnguyen800** [comment]
thanks for letting me know. I've updated the documentation to reflect the change.
