### ISSUE TITLE
Playlist doesn't have image

### ISSUE THREAD

**Issue by klejejs** [dnguyen800/spotify-playlist-sensor#4]
Hi.
Some playlists you create on Spotify doesn't have an image so the component crashes. I found a solution: you have to change the line 
```image = playlist['images'][0]['url']```
to 
```
try:
    image = playlist['images'][0]['url']
except:
    image = ''
```

**Comment by dnguyen800** [comment]
Thanks for noting this. I'll add your fix to the next release.

**Comment by dnguyen800** [comment]
Added code in latest release.
