### ISSUE TITLE
INVALID_CLIENT: Invalid redirect URI

### ISSUE THREAD

**Issue by gogui63** [dnguyen800/Spotify-Playlist-Sensor#5]
Hello, thanks for your spotify integration but I've an issue

- I'm runing with hass 0.105.1
- I deleted all old tokens of spotify
- I created a new app in spotify dev account just for this integration

My url to authorize is like this : 
https://accounts.spotify.com/authorize?client_id=xxxxxxxxx&response_type=code&redirect_uri=https%3A%2F%2Fmydomain.com%2Fapi%2Fspotify&scope=playlist-read-private+user-modify-playback-state+user-read-playback-state+user-read-private

An error when I tried to authorize : 
`INVALID_CLIENT: Invalid redirect URI`

Do you have an idea why it doesn't work ? 

Thanks

**Comment by gogui63** [comment]
You can close... I'm stupid and didn't read all instructions.. 
I forgot redirect URI
Sorry :)

**Comment by pergolafabio** [comment]
how did you resolve?
because i did upgrade to 105.x too, i cant authorize anymore
seems the HA spotify plugin also changed, the call back address is now : https://www.home-assistant.io/integrations/spotify

 https://<your_home_assistant_url_or_local_ip>/auth/external/callback

i see in your url it still points to api/spotify ... but that doesnt excists anymore ?

**Comment by gogui63** [comment]
On your Spotify dev account add in "Redirect Uri" : https://<your_home_assistant_url>/api/spotify
You should use external and secure (http**s**) url

On my side I created a new app for this integration, one for global spotify integration and an other one for this plugin.

**Comment by pergolafabio** [comment]
yeah, i am using nabucasa, i use that url
but i now created 2 apps on developer website , one with new auth url for the media player component, and one for this sensor

so both apps are using : /auth/external/callback & api/spotify
both with nabucasa

seems api/spotify still works

also fixed now here
